/*
 * This file is part of the SweetCherry project.
 * Please refer to the project's README.md file for additional details.
 * https://github.com/turkerozturk/SweetCherry
 *
 * Copyright (c) 2024 Turker Ozturk
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/gpl-3.0.en.html>.
 */
package com.turkerozturk.helpers.highlighter.pygments;

public enum LexerEnum {
    ACTIONSCRIPT3_LEXER("actionscript3", "ActionScript3Lexer", "pygments.lexers.actionscript.ActionScript3Lexer"),
    ACTIONSCRIPT_LEXER("actionscript", "ActionScriptLexer", "pygments.lexers.actionscript.ActionScriptLexer"),
    MXML_LEXER("mxml", "MxmlLexer", "pygments.lexers.actionscript.MxmlLexer"),
    ADA_LEXER("ada", "AdaLexer", "pygments.lexers.ada.AdaLexer"),
    BC_LEXER("bc", "BCLexer", "pygments.lexers.algebra.BCLexer"),
    GAPCONSOLE_LEXER("gapconsole", "GAPConsoleLexer", "pygments.lexers.algebra.GAPConsoleLexer"),
    GAP_LEXER("gap", "GAPLexer", "pygments.lexers.algebra.GAPLexer"),
    MATHEMATICA_LEXER("mathematica", "MathematicaLexer", "pygments.lexers.algebra.MathematicaLexer"),
    MUPAD_LEXER("mupad", "MuPADLexer", "pygments.lexers.algebra.MuPADLexer"),
    AMBIENTTALK_LEXER("ambienttalk", "AmbientTalkLexer", "pygments.lexers.ambient.AmbientTalkLexer"),
    AMDGPU_LEXER("amdgpu", "AMDGPULexer", "pygments.lexers.amdgpu.AMDGPULexer"),
    AMPL_LEXER("ampl", "AmplLexer", "pygments.lexers.ampl.AmplLexer"),
    APD_LEXER("apd", "apdlexer", "pygments.lexers.apdlexer.apdlexer"),
    APL_LEXER("apl", "APLLexer", "pygments.lexers.apl.APLLexer"),
    ADL_LEXER("adl", "AdlLexer", "pygments.lexers.archetype.AdlLexer"),
    CADL_LEXER("cadl", "CadlLexer", "pygments.lexers.archetype.CadlLexer"),
    ODIN_LEXER("odin", "OdinLexer", "pygments.lexers.archetype.OdinLexer"),
    ARROW_LEXER("arrow", "ArrowLexer", "pygments.lexers.arrow.ArrowLexer"),
    ARTURO_LEXER("arturo", "ArturoLexer", "pygments.lexers.arturo.ArturoLexer"),
    ASC_LEXER("asc", "AscLexer", "pygments.lexers.asc.AscLexer"),
    COBJDUMP_LEXER("cobjdump", "CObjdumpLexer", "pygments.lexers.asm.CObjdumpLexer"),
    CA65_LEXER("ca65", "Ca65Lexer", "pygments.lexers.asm.Ca65Lexer"),
    CPPOBJDUMP_LEXER("cppobjdump", "CppObjdumpLexer", "pygments.lexers.asm.CppObjdumpLexer"),
    DOBJDUMP_LEXER("dobjdump", "DObjdumpLexer", "pygments.lexers.asm.DObjdumpLexer"),
    DASM16_LEXER("dasm16", "Dasm16Lexer", "pygments.lexers.asm.Dasm16Lexer"),
    GAS_LEXER("gas", "GasLexer", "pygments.lexers.asm.GasLexer"),
    HSAIL_LEXER("hsail", "HsailLexer", "pygments.lexers.asm.HsailLexer"),
    LLVM_LEXER("llvm", "LlvmLexer", "pygments.lexers.asm.LlvmLexer"),
    LLVMMIRBODY_LEXER("llvmmirbody", "LlvmMirBodyLexer", "pygments.lexers.asm.LlvmMirBodyLexer"),
    LLVMMIR_LEXER("llvmmir", "LlvmMirLexer", "pygments.lexers.asm.LlvmMirLexer"),
    NASM_LEXER("nasm", "NasmLexer", "pygments.lexers.asm.NasmLexer"),
    NASMOBJDUMP_LEXER("nasmobjdump", "NasmObjdumpLexer", "pygments.lexers.asm.NasmObjdumpLexer"),
    OBJDUMP_LEXER("objdump", "ObjdumpLexer", "pygments.lexers.asm.ObjdumpLexer"),
    TASM_LEXER("tasm", "TasmLexer", "pygments.lexers.asm.TasmLexer"),
    ASN1_LEXER("asn1", "Asn1Lexer", "pygments.lexers.asn1.Asn1Lexer"),
    AUTOIT_LEXER("autoit", "AutoItLexer", "pygments.lexers.automation.AutoItLexer"),
    AUTOHOTKEY_LEXER("autohotkey", "AutohotkeyLexer", "pygments.lexers.automation.AutohotkeyLexer"),
    BARE_LEXER("bare", "BareLexer", "pygments.lexers.bare.BareLexer"),
    BBCBASIC_LEXER("bbcbasic", "BBCBasicLexer", "pygments.lexers.basic.BBCBasicLexer"),
    BLITZBASIC_LEXER("blitzbasic", "BlitzBasicLexer", "pygments.lexers.basic.BlitzBasicLexer"),
    BLITZMAX_LEXER("blitzmax", "BlitzMaxLexer", "pygments.lexers.basic.BlitzMaxLexer"),
    CBMBASICV2_LEXER("cbmbasicv2", "CbmBasicV2Lexer", "pygments.lexers.basic.CbmBasicV2Lexer"),
    MONKEY_LEXER("monkey", "MonkeyLexer", "pygments.lexers.basic.MonkeyLexer"),
    QBASIC_LEXER("qbasic", "QBasicLexer", "pygments.lexers.basic.QBasicLexer"),
    VBSCRIPT_LEXER("vbscript", "VBScriptLexer", "pygments.lexers.basic.VBScriptLexer"),
    BDD_LEXER("bdd", "BddLexer", "pygments.lexers.bdd.BddLexer"),
    BERRY_LEXER("berry", "BerryLexer", "pygments.lexers.berry.BerryLexer"),
    BST_LEXER("bst", "BSTLexer", "pygments.lexers.bibtex.BSTLexer"),
    BIBTEX_LEXER("bibtex", "BibTeXLexer", "pygments.lexers.bibtex.BibTeXLexer"),
    BLUEPRINT_LEXER("blueprint", "BlueprintLexer", "pygments.lexers.blueprint.BlueprintLexer"),
    BOA_LEXER("boa", "BoaLexer", "pygments.lexers.boa.BoaLexer"),
    BQN_LEXER("bqn", "BQNLexer", "pygments.lexers.bqn.BQNLexer"),
    ABAP_LEXER("abap", "ABAPLexer", "pygments.lexers.business.ABAPLexer"),
    COBOLFREEFORMAT_LEXER("cobolfreeformat", "CobolFreeformatLexer", "pygments.lexers.business.CobolFreeformatLexer"),
    COBOL_LEXER("cobol", "CobolLexer", "pygments.lexers.business.CobolLexer"),
    GOODDATACL_LEXER("gooddatacl", "GoodDataCLLexer", "pygments.lexers.business.GoodDataCLLexer"),
    MAQL_LEXER("maql", "MaqlLexer", "pygments.lexers.business.MaqlLexer"),
    OPENEDGE_LEXER("openedge", "OpenEdgeLexer", "pygments.lexers.business.OpenEdgeLexer"),
    C_LEXER("c", "CLexer", "pygments.lexers.c_cpp.CLexer"),
    CPP_LEXER("cpp", "CppLexer", "pygments.lexers.c_cpp.CppLexer"),
    ARDUINO_LEXER("arduino", "ArduinoLexer", "pygments.lexers.c_like.ArduinoLexer"),
    CHARMCI_LEXER("charmci", "CharmciLexer", "pygments.lexers.c_like.CharmciLexer"),
    CLAY_LEXER("clay", "ClayLexer", "pygments.lexers.c_like.ClayLexer"),
    CUDA_LEXER("cuda", "CudaLexer", "pygments.lexers.c_like.CudaLexer"),
    EC_LEXER("ec", "ECLexer", "pygments.lexers.c_like.ECLexer"),
    MQL_LEXER("mql", "MqlLexer", "pygments.lexers.c_like.MqlLexer"),
    NESC_LEXER("nesc", "NesCLexer", "pygments.lexers.c_like.NesCLexer"),
    OMGIDL_LEXER("omgidl", "OmgIdlLexer", "pygments.lexers.c_like.OmgIdlLexer"),
    PIKE_LEXER("pike", "PikeLexer", "pygments.lexers.c_like.PikeLexer"),
    PROMELA_LEXER("promela", "PromelaLexer", "pygments.lexers.c_like.PromelaLexer"),
    SWIG_LEXER("swig", "SwigLexer", "pygments.lexers.c_like.SwigLexer"),
    VALA_LEXER("vala", "ValaLexer", "pygments.lexers.c_like.ValaLexer"),
    CAPNPROTO_LEXER("capnproto", "CapnProtoLexer", "pygments.lexers.capnproto.CapnProtoLexer"),
    CARBON_LEXER("carbon", "CarbonLexer", "pygments.lexers.carbon.CarbonLexer"),
    CDDL_LEXER("cddl", "CddlLexer", "pygments.lexers.cddl.CddlLexer"),
    CHAPEL_LEXER("chapel", "ChapelLexer", "pygments.lexers.chapel.ChapelLexer"),
    CLEAN_LEXER("clean", "CleanLexer", "pygments.lexers.clean.CleanLexer"),
    COMAL80_LEXER("comal80", "Comal80Lexer", "pygments.lexers.comal.Comal80Lexer"),
    APACHECONF_LEXER("apacheconf", "ApacheConfLexer", "pygments.lexers.configs.ApacheConfLexer"),
    AUGEAS_LEXER("augeas", "AugeasLexer", "pygments.lexers.configs.AugeasLexer"),
    CFENGINE3_LEXER("cfengine3", "Cfengine3Lexer", "pygments.lexers.configs.Cfengine3Lexer"),
    DESKTOP_LEXER("desktop", "DesktopLexer", "pygments.lexers.configs.DesktopLexer"),
    DOCKER_LEXER("docker", "DockerLexer", "pygments.lexers.configs.DockerLexer"),
    INI_LEXER("ini", "IniLexer", "pygments.lexers.configs.IniLexer"),
    KCONFIG_LEXER("kconfig", "KconfigLexer", "pygments.lexers.configs.KconfigLexer"),
    LIGHTTPDCONF_LEXER("lighttpdconf", "LighttpdConfLexer", "pygments.lexers.configs.LighttpdConfLexer"),
    NESTEDTEXT_LEXER("nestedtext", "NestedTextLexer", "pygments.lexers.configs.NestedTextLexer"),
    NGINXCONF_LEXER("nginxconf", "NginxConfLexer", "pygments.lexers.configs.NginxConfLexer"),
    PACMANCONF_LEXER("pacmanconf", "PacmanConfLexer", "pygments.lexers.configs.PacmanConfLexer"),
    PKGCONFIG_LEXER("pkgconfig", "PkgConfigLexer", "pygments.lexers.configs.PkgConfigLexer"),
    PROPERTIES_LEXER("properties", "PropertiesLexer", "pygments.lexers.configs.PropertiesLexer"),
    REGEDIT_LEXER("regedit", "RegeditLexer", "pygments.lexers.configs.RegeditLexer"),
    SINGULARITY_LEXER("singularity", "SingularityLexer", "pygments.lexers.configs.SingularityLexer"),
    SQUIDCONF_LEXER("squidconf", "SquidConfLexer", "pygments.lexers.configs.SquidConfLexer"),
    SYSTEMD_LEXER("systemd", "SystemdLexer", "pygments.lexers.configs.SystemdLexer"),
    TOML_LEXER("toml", "TOMLLexer", "pygments.lexers.configs.TOMLLexer"),
    TERMCAP_LEXER("termcap", "TermcapLexer", "pygments.lexers.configs.TermcapLexer"),
    TERMINFO_LEXER("terminfo", "TerminfoLexer", "pygments.lexers.configs.TerminfoLexer"),
    TERRAFORM_LEXER("terraform", "TerraformLexer", "pygments.lexers.configs.TerraformLexer"),
    UNIXCONFIG_LEXER("unixconfig", "UnixConfigLexer", "pygments.lexers.configs.UnixConfigLexer"),
    PYPYLOG_LEXER("pypylog", "PyPyLogLexer", "pygments.lexers.console.PyPyLogLexer"),
    VCTREESTATUS_LEXER("vctreestatus", "VCTreeStatusLexer", "pygments.lexers.console.VCTreeStatusLexer"),
    CPLINT_LEXER("cplint", "CplintLexer", "pygments.lexers.cplint.CplintLexer"),
    CRYSTAL_LEXER("crystal", "CrystalLexer", "pygments.lexers.crystal.CrystalLexer"),
    CSOUNDDOCUMENT_LEXER("csounddocument", "CsoundDocumentLexer", "pygments.lexers.csound.CsoundDocumentLexer"),
    CSOUNDORCHESTRA_LEXER("csoundorchestra", "CsoundOrchestraLexer", "pygments.lexers.csound.CsoundOrchestraLexer"),
    CSOUNDSCORE_LEXER("csoundscore", "CsoundScoreLexer", "pygments.lexers.csound.CsoundScoreLexer"),
    CSS_LEXER("css", "CssLexer", "pygments.lexers.css.CssLexer"),
    LESSCSS_LEXER("lesscss", "LessCssLexer", "pygments.lexers.css.LessCssLexer"),
    SASS_LEXER("sass", "SassLexer", "pygments.lexers.css.SassLexer"),
    SCSS_LEXER("scss", "ScssLexer", "pygments.lexers.css.ScssLexer"),
    CROC_LEXER("croc", "CrocLexer", "pygments.lexers.d.CrocLexer"),
    D_LEXER("d", "DLexer", "pygments.lexers.d.DLexer"),
    MINID_LEXER("minid", "MiniDLexer", "pygments.lexers.d.MiniDLexer"),
    JSONBAREOBJECT_LEXER("jsonbareobject", "JsonBareObjectLexer", "pygments.lexers.data.JsonBareObjectLexer"),
    JSONLD_LEXER("jsonld", "JsonLdLexer", "pygments.lexers.data.JsonLdLexer"),
    JSON_LEXER("json", "JsonLexer", "pygments.lexers.data.JsonLexer"),
    YAML_LEXER("yaml", "YamlLexer", "pygments.lexers.data.YamlLexer"),
    DAX_LEXER("dax", "DaxLexer", "pygments.lexers.dax.DaxLexer"),
    DEVICETREE_LEXER("devicetree", "DevicetreeLexer", "pygments.lexers.devicetree.DevicetreeLexer"),
    DARCSPATCH_LEXER("darcspatch", "DarcsPatchLexer", "pygments.lexers.diff.DarcsPatchLexer"),
    DIFF_LEXER("diff", "DiffLexer", "pygments.lexers.diff.DiffLexer"),
    WDIFF_LEXER("wdiff", "WDiffLexer", "pygments.lexers.diff.WDiffLexer"),
    DNSZONE_LEXER("dnszone", "DnsZoneLexer", "pygments.lexers.dns.DnsZoneLexer"),
    BOO_LEXER("boo", "BooLexer", "pygments.lexers.dotnet.BooLexer"),
    CSHARPASPX_LEXER("csharpaspx", "CSharpAspxLexer", "pygments.lexers.dotnet.CSharpAspxLexer"),
    CSHARP_LEXER("csharp", "CSharpLexer", "pygments.lexers.dotnet.CSharpLexer"),
    FSHARP_LEXER("fsharp", "FSharpLexer", "pygments.lexers.dotnet.FSharpLexer"),
    NEMERLE_LEXER("nemerle", "NemerleLexer", "pygments.lexers.dotnet.NemerleLexer"),
    VBNETASPX_LEXER("vbnetaspx", "VbNetAspxLexer", "pygments.lexers.dotnet.VbNetAspxLexer"),
    VBNET_LEXER("vbnet", "VbNetLexer", "pygments.lexers.dotnet.VbNetLexer"),
    XPP_LEXER("xpp", "XppLexer", "pygments.lexers.dotnet.XppLexer"),
    ALLOY_LEXER("alloy", "AlloyLexer", "pygments.lexers.dsls.AlloyLexer"),
    CRMSH_LEXER("crmsh", "CrmshLexer", "pygments.lexers.dsls.CrmshLexer"),
    FLATLINE_LEXER("flatline", "FlatlineLexer", "pygments.lexers.dsls.FlatlineLexer"),
    MSCGEN_LEXER("mscgen", "MscgenLexer", "pygments.lexers.dsls.MscgenLexer"),
    PAN_LEXER("pan", "PanLexer", "pygments.lexers.dsls.PanLexer"),
    PROTOBUF_LEXER("protobuf", "ProtoBufLexer", "pygments.lexers.dsls.ProtoBufLexer"),
    PUPPET_LEXER("puppet", "PuppetLexer", "pygments.lexers.dsls.PuppetLexer"),
    RSL_LEXER("rsl", "RslLexer", "pygments.lexers.dsls.RslLexer"),
    SNOWBALL_LEXER("snowball", "SnowballLexer", "pygments.lexers.dsls.SnowballLexer"),
    THRIFT_LEXER("thrift", "ThriftLexer", "pygments.lexers.dsls.ThriftLexer"),
    VGL_LEXER("vgl", "VGLLexer", "pygments.lexers.dsls.VGLLexer"),
    ZEEK_LEXER("zeek", "ZeekLexer", "pygments.lexers.dsls.ZeekLexer"),
    DYLANCONSOLE_LEXER("dylanconsole", "DylanConsoleLexer", "pygments.lexers.dylan.DylanConsoleLexer"),
    DYLAN_LEXER("dylan", "DylanLexer", "pygments.lexers.dylan.DylanLexer"),
    DYLANLID_LEXER("dylanlid", "DylanLidLexer", "pygments.lexers.dylan.DylanLidLexer"),
    ECL_LEXER("ecl", "ECLLexer", "pygments.lexers.ecl.ECLLexer"),
    EIFFEL_LEXER("eiffel", "EiffelLexer", "pygments.lexers.eiffel.EiffelLexer"),
    ELM_LEXER("elm", "ElmLexer", "pygments.lexers.elm.ElmLexer"),
    ELPI_LEXER("elpi", "ElpiLexer", "pygments.lexers.elpi.ElpiLexer"),
    EMAIL_LEXER("email", "EmailLexer", "pygments.lexers.email.EmailLexer"),
    ELIXIRCONSOLE_LEXER("elixirconsole", "ElixirConsoleLexer", "pygments.lexers.erlang.ElixirConsoleLexer"),
    ELIXIR_LEXER("elixir", "ElixirLexer", "pygments.lexers.erlang.ElixirLexer"),
    ERLANG_LEXER("erlang", "ErlangLexer", "pygments.lexers.erlang.ErlangLexer"),
    ERLANGSHELL_LEXER("erlangshell", "ErlangShellLexer", "pygments.lexers.erlang.ErlangShellLexer"),
    AHEUI_LEXER("aheui", "AheuiLexer", "pygments.lexers.esoteric.AheuiLexer"),
    BEFUNGE_LEXER("befunge", "BefungeLexer", "pygments.lexers.esoteric.BefungeLexer"),
    BRAINFUCK_LEXER("brainfuck", "BrainfuckLexer", "pygments.lexers.esoteric.BrainfuckLexer"),
    CAMKES_LEXER("camkes", "CAmkESLexer", "pygments.lexers.esoteric.CAmkESLexer"),
    CAPDL_LEXER("capdl", "CapDLLexer", "pygments.lexers.esoteric.CapDLLexer"),
    REDCODE_LEXER("redcode", "RedcodeLexer", "pygments.lexers.esoteric.RedcodeLexer"),
    EZHIL_LEXER("ezhil", "EzhilLexer", "pygments.lexers.ezhil.EzhilLexer"),
    FACTOR_LEXER("factor", "FactorLexer", "pygments.lexers.factor.FactorLexer"),
    FANTOM_LEXER("fantom", "FantomLexer", "pygments.lexers.fantom.FantomLexer"),
    FELIX_LEXER("felix", "FelixLexer", "pygments.lexers.felix.FelixLexer"),
    FIFT_LEXER("fift", "FiftLexer", "pygments.lexers.fift.FiftLexer"),
    FLOSCRIPT_LEXER("floscript", "FloScriptLexer", "pygments.lexers.floscript.FloScriptLexer"),
    FORTH_LEXER("forth", "ForthLexer", "pygments.lexers.forth.ForthLexer"),
    FORTRANFIXED_LEXER("fortranfixed", "FortranFixedLexer", "pygments.lexers.fortran.FortranFixedLexer"),
    FORTRAN_LEXER("fortran", "FortranLexer", "pygments.lexers.fortran.FortranLexer"),
    FOXPRO_LEXER("foxpro", "FoxProLexer", "pygments.lexers.foxpro.FoxProLexer"),
    FREEFEM_LEXER("freefem", "FreeFemLexer", "pygments.lexers.freefem.FreeFemLexer"),
    FUNC_LEXER("func", "FuncLexer", "pygments.lexers.func.FuncLexer"),
    FUTHARK_LEXER("futhark", "FutharkLexer", "pygments.lexers.futhark.FutharkLexer"),
    GCODE_LEXER("gcode", "GcodeLexer", "pygments.lexers.gcodelexer.GcodeLexer"),
    GDSCRIPT_LEXER("gdscript", "GDScriptLexer", "pygments.lexers.gdscript.GDScriptLexer"),
    GO_LEXER("go", "GoLexer", "pygments.lexers.go.GoLexer"),
    ABNF_LEXER("abnf", "AbnfLexer", "pygments.lexers.grammar_notation.AbnfLexer"),
    BNF_LEXER("bnf", "BnfLexer", "pygments.lexers.grammar_notation.BnfLexer"),
    JSGF_LEXER("jsgf", "JsgfLexer", "pygments.lexers.grammar_notation.JsgfLexer"),
    PEG_LEXER("peg", "PegLexer", "pygments.lexers.grammar_notation.PegLexer"),
    CYPHER_LEXER("cypher", "CypherLexer", "pygments.lexers.graph.CypherLexer"),
    ASYMPTOTE_LEXER("asymptote", "AsymptoteLexer", "pygments.lexers.graphics.AsymptoteLexer"),
    GLSHADER_LEXER("glshader", "GLShaderLexer", "pygments.lexers.graphics.GLShaderLexer"),
    GNUPLOT_LEXER("gnuplot", "GnuplotLexer", "pygments.lexers.graphics.GnuplotLexer"),
    HLSLSHADER_LEXER("hlslshader", "HLSLShaderLexer", "pygments.lexers.graphics.HLSLShaderLexer"),
    POSTSCRIPT_LEXER("postscript", "PostScriptLexer", "pygments.lexers.graphics.PostScriptLexer"),
    POVRAY_LEXER("povray", "PovrayLexer", "pygments.lexers.graphics.PovrayLexer"),
    GRAPHQL_LEXER("graphql", "GraphQLLexer", "pygments.lexers.graphql.GraphQLLexer"),
    GRAPHVIZ_LEXER("graphviz", "GraphvizLexer", "pygments.lexers.graphviz.GraphvizLexer"),
    GSQL_LEXER("gsql", "GSQLLexer", "pygments.lexers.gsql.GSQLLexer"),
    AGDA_LEXER("agda", "AgdaLexer", "pygments.lexers.haskell.AgdaLexer"),
    CRYPTOL_LEXER("cryptol", "CryptolLexer", "pygments.lexers.haskell.CryptolLexer"),
    HASKELL_LEXER("haskell", "HaskellLexer", "pygments.lexers.haskell.HaskellLexer"),
    HSPEC_LEXER("hspec", "HspecLexer", "pygments.lexers.haskell.HspecLexer"),
    IDRIS_LEXER("idris", "IdrisLexer", "pygments.lexers.haskell.IdrisLexer"),
    KOKA_LEXER("koka", "KokaLexer", "pygments.lexers.haskell.KokaLexer"),
    LITERATEAGDA_LEXER("literateagda", "LiterateAgdaLexer", "pygments.lexers.haskell.LiterateAgdaLexer"),
    LITERATECRYPTOL_LEXER("literatecryptol", "LiterateCryptolLexer", "pygments.lexers.haskell.LiterateCryptolLexer"),
    LITERATEHASKELL_LEXER("literatehaskell", "LiterateHaskellLexer", "pygments.lexers.haskell.LiterateHaskellLexer"),
    LITERATEIDRIS_LEXER("literateidris", "LiterateIdrisLexer", "pygments.lexers.haskell.LiterateIdrisLexer"),
    HAXE_LEXER("haxe", "HaxeLexer", "pygments.lexers.haxe.HaxeLexer"),
    HXML_LEXER("hxml", "HxmlLexer", "pygments.lexers.haxe.HxmlLexer"),
    SYSTEMVERILOG_LEXER("systemverilog", "SystemVerilogLexer", "pygments.lexers.hdl.SystemVerilogLexer"),
    VERILOG_LEXER("verilog", "VerilogLexer", "pygments.lexers.hdl.VerilogLexer"),
    VHDL_LEXER("vhdl", "VhdlLexer", "pygments.lexers.hdl.VhdlLexer"),
    HEXDUMP_LEXER("hexdump", "HexdumpLexer", "pygments.lexers.hexdump.HexdumpLexer"),
    DTD_LEXER("dtd", "DtdLexer", "pygments.lexers.html.DtdLexer"),
    HAML_LEXER("haml", "HamlLexer", "pygments.lexers.html.HamlLexer"),
    HTML_LEXER("html", "HtmlLexer", "pygments.lexers.html.HtmlLexer"),
    PUG_LEXER("pug", "PugLexer", "pygments.lexers.html.PugLexer"),
    SCAML_LEXER("scaml", "ScamlLexer", "pygments.lexers.html.ScamlLexer"),
    URLENCODED_LEXER("urlencoded", "UrlEncodedLexer", "pygments.lexers.html.UrlEncodedLexer"),
    XML_LEXER("xml", "XmlLexer", "pygments.lexers.html.XmlLexer"),
    XSLT_LEXER("xslt", "XsltLexer", "pygments.lexers.html.XsltLexer"),
    IDL_LEXER("idl", "IDLLexer", "pygments.lexers.idl.IDLLexer"),
    IGOR_LEXER("igor", "IgorLexer", "pygments.lexers.igor.IgorLexer"),
    LIMBO_LEXER("limbo", "LimboLexer", "pygments.lexers.inferno.LimboLexer"),
    DEBIANCONTROL_LEXER("debiancontrol", "DebianControlLexer", "pygments.lexers.installers.DebianControlLexer"),
    NSIS_LEXER("nsis", "NSISLexer", "pygments.lexers.installers.NSISLexer"),
    RPMSPEC_LEXER("rpmspec", "RPMSpecLexer", "pygments.lexers.installers.RPMSpecLexer"),
    SOURCESLIST_LEXER("sourceslist", "SourcesListLexer", "pygments.lexers.installers.SourcesListLexer"),
    INFORM6_LEXER("inform6", "Inform6Lexer", "pygments.lexers.int_fiction.Inform6Lexer"),
    INFORM6TEMPLATE_LEXER("inform6template", "Inform6TemplateLexer", "pygments.lexers.int_fiction.Inform6TemplateLexer"),
    INFORM7_LEXER("inform7", "Inform7Lexer", "pygments.lexers.int_fiction.Inform7Lexer"),
    TADS3_LEXER("tads3", "Tads3Lexer", "pygments.lexers.int_fiction.Tads3Lexer"),
    IO_LEXER("io", "IoLexer", "pygments.lexers.iolang.IoLexer"),
    J_LEXER("j", "JLexer", "pygments.lexers.j.JLexer"),
    COFFEESCRIPT_LEXER("coffeescript", "CoffeeScriptLexer", "pygments.lexers.javascript.CoffeeScriptLexer"),
    DART_LEXER("dart", "DartLexer", "pygments.lexers.javascript.DartLexer"),
    EARLGREY_LEXER("earlgrey", "EarlGreyLexer", "pygments.lexers.javascript.EarlGreyLexer"),
    JAVASCRIPT_LEXER("javascript", "JavascriptLexer", "pygments.lexers.javascript.JavascriptLexer"),
    JUTTLE_LEXER("juttle", "JuttleLexer", "pygments.lexers.javascript.JuttleLexer"),
    KAL_LEXER("kal", "KalLexer", "pygments.lexers.javascript.KalLexer"),
    LASSO_LEXER("lasso", "LassoLexer", "pygments.lexers.javascript.LassoLexer"),
    LIVESCRIPT_LEXER("livescript", "LiveScriptLexer", "pygments.lexers.javascript.LiveScriptLexer"),
    MASK_LEXER("mask", "MaskLexer", "pygments.lexers.javascript.MaskLexer"),
    NODECONSOLE_LEXER("nodeconsole", "NodeConsoleLexer", "pygments.lexers.javascript.NodeConsoleLexer"),
    OBJECTIVEJ_LEXER("objectivej", "ObjectiveJLexer", "pygments.lexers.javascript.ObjectiveJLexer"),
    TYPESCRIPT_LEXER("typescript", "TypeScriptLexer", "pygments.lexers.javascript.TypeScriptLexer"),
    JMESPATH_LEXER("jmespath", "JMESPathLexer", "pygments.lexers.jmespath.JMESPathLexer"),
    JSLT_LEXER("jslt", "JSLTLexer", "pygments.lexers.jslt.JSLTLexer"),
    JSONNET_LEXER("jsonnet", "JsonnetLexer", "pygments.lexers.jsonnet.JsonnetLexer"),
    JSX_LEXER("jsx", "JsxLexer", "pygments.lexers.jsx.JsxLexer"),
    JULIACONSOLE_LEXER("juliaconsole", "JuliaConsoleLexer", "pygments.lexers.julia.JuliaConsoleLexer"),
    JULIA_LEXER("julia", "JuliaLexer", "pygments.lexers.julia.JuliaLexer"),
    ASPECTJ_LEXER("aspectj", "AspectJLexer", "pygments.lexers.jvm.AspectJLexer"),
    CEYLON_LEXER("ceylon", "CeylonLexer", "pygments.lexers.jvm.CeylonLexer"),
    CLOJURE_LEXER("clojure", "ClojureLexer", "pygments.lexers.jvm.ClojureLexer"),
    CLOJURESCRIPT_LEXER("clojurescript", "ClojureScriptLexer", "pygments.lexers.jvm.ClojureScriptLexer"),
    GOLO_LEXER("golo", "GoloLexer", "pygments.lexers.jvm.GoloLexer"),
    GOSU_LEXER("gosu", "GosuLexer", "pygments.lexers.jvm.GosuLexer"),
    GOSUTEMPLATE_LEXER("gosutemplate", "GosuTemplateLexer", "pygments.lexers.jvm.GosuTemplateLexer"),
    GROOVY_LEXER("groovy", "GroovyLexer", "pygments.lexers.jvm.GroovyLexer"),
    IOKE_LEXER("ioke", "IokeLexer", "pygments.lexers.jvm.IokeLexer"),
    JASMIN_LEXER("jasmin", "JasminLexer", "pygments.lexers.jvm.JasminLexer"),
    JAVA_LEXER("java", "JavaLexer", "pygments.lexers.jvm.JavaLexer"),
    KOTLIN_LEXER("kotlin", "KotlinLexer", "pygments.lexers.jvm.KotlinLexer"),
    PIG_LEXER("pig", "PigLexer", "pygments.lexers.jvm.PigLexer"),
    SARL_LEXER("sarl", "SarlLexer", "pygments.lexers.jvm.SarlLexer"),
    SCALA_LEXER("scala", "ScalaLexer", "pygments.lexers.jvm.ScalaLexer"),
    XTEND_LEXER("xtend", "XtendLexer", "pygments.lexers.jvm.XtendLexer"),
    KUIN_LEXER("kuin", "KuinLexer", "pygments.lexers.kuin.KuinLexer"),
    KUSTO_LEXER("kusto", "KustoLexer", "pygments.lexers.kusto.KustoLexer"),
    LDAPRC_LEXER("ldaprc", "LdaprcLexer", "pygments.lexers.ldap.LdaprcLexer"),
    LDIF_LEXER("ldif", "LdifLexer", "pygments.lexers.ldap.LdifLexer"),
    LEAN3_LEXER("lean3", "Lean3Lexer", "pygments.lexers.lean.Lean3Lexer"),
    LEAN4_LEXER("lean4", "Lean4Lexer", "pygments.lexers.lean.Lean4Lexer"),
    LILYPOND_LEXER("lilypond", "LilyPondLexer", "pygments.lexers.lilypond.LilyPondLexer"),
    CPSA_LEXER("cpsa", "CPSALexer", "pygments.lexers.lisp.CPSALexer"),
    COMMONLISP_LEXER("commonlisp", "CommonLispLexer", "pygments.lexers.lisp.CommonLispLexer"),
    EMACSLISP_LEXER("emacslisp", "EmacsLispLexer", "pygments.lexers.lisp.EmacsLispLexer"),
    FENNEL_LEXER("fennel", "FennelLexer", "pygments.lexers.lisp.FennelLexer"),
    HY_LEXER("hy", "HyLexer", "pygments.lexers.lisp.HyLexer"),
    JANET_LEXER("janet", "JanetLexer", "pygments.lexers.lisp.JanetLexer"),
    NEWLISP_LEXER("newlisp", "NewLispLexer", "pygments.lexers.lisp.NewLispLexer"),
    RACKET_LEXER("racket", "RacketLexer", "pygments.lexers.lisp.RacketLexer"),
    SCHEME_LEXER("scheme", "SchemeLexer", "pygments.lexers.lisp.SchemeLexer"),
    SHEN_LEXER("shen", "ShenLexer", "pygments.lexers.lisp.ShenLexer"),
    XTLANG_LEXER("xtlang", "XtlangLexer", "pygments.lexers.lisp.XtlangLexer"),
    MACAULAY2_LEXER("macaulay2", "Macaulay2Lexer", "pygments.lexers.macaulay2.Macaulay2Lexer"),
    BASEMAKEFILE_LEXER("basemakefile", "BaseMakefileLexer", "pygments.lexers.make.BaseMakefileLexer"),
    CMAKE_LEXER("cmake", "CMakeLexer", "pygments.lexers.make.CMakeLexer"),
    MAKEFILE_LEXER("makefile", "MakefileLexer", "pygments.lexers.make.MakefileLexer"),
    BBCODE_LEXER("bbcode", "BBCodeLexer", "pygments.lexers.markup.BBCodeLexer"),
    GROFF_LEXER("groff", "GroffLexer", "pygments.lexers.markup.GroffLexer"),
    MARKDOWN_LEXER("markdown", "MarkdownLexer", "pygments.lexers.markup.MarkdownLexer"),
    MOINWIKI_LEXER("moinwiki", "MoinWikiLexer", "pygments.lexers.markup.MoinWikiLexer"),
    MOZPREPROCCSS_LEXER("mozpreproccss", "MozPreprocCssLexer", "pygments.lexers.markup.MozPreprocCssLexer"),
    MOZPREPROCHASH_LEXER("mozpreprochash", "MozPreprocHashLexer", "pygments.lexers.markup.MozPreprocHashLexer"),
    MOZPREPROCJAVASCRIPT_LEXER("mozpreprocjavascript", "MozPreprocJavascriptLexer", "pygments.lexers.markup.MozPreprocJavascriptLexer"),
    MOZPREPROCPERCENT_LEXER("mozpreprocpercent", "MozPreprocPercentLexer", "pygments.lexers.markup.MozPreprocPercentLexer"),
    MOZPREPROCXUL_LEXER("mozpreprocxul", "MozPreprocXulLexer", "pygments.lexers.markup.MozPreprocXulLexer"),
    RST_LEXER("rst", "RstLexer", "pygments.lexers.markup.RstLexer"),
    TEX_LEXER("tex", "TexLexer", "pygments.lexers.markup.TexLexer"),
    TIDDLYWIKI5_LEXER("tiddlywiki5", "TiddlyWiki5Lexer", "pygments.lexers.markup.TiddlyWiki5Lexer"),
    WIKITEXT_LEXER("wikitext", "WikitextLexer", "pygments.lexers.markup.WikitextLexer"),
    MATLAB_LEXER("matlab", "MatlabLexer", "pygments.lexers.matlab.MatlabLexer"),
    MATLABSESSION_LEXER("matlabsession", "MatlabSessionLexer", "pygments.lexers.matlab.MatlabSessionLexer"),
    OCTAVE_LEXER("octave", "OctaveLexer", "pygments.lexers.matlab.OctaveLexer"),
    SCILAB_LEXER("scilab", "ScilabLexer", "pygments.lexers.matlab.ScilabLexer"),
    MAXIMA_LEXER("maxima", "MaximaLexer", "pygments.lexers.maxima.MaximaLexer"),
    MESON_LEXER("meson", "MesonLexer", "pygments.lexers.meson.MesonLexer"),
    MIME_LEXER("mime", "MIMELexer", "pygments.lexers.mime.MIMELexer"),
    MIPS_LEXER("mips", "MIPSLexer", "pygments.lexers.mips.MIPSLexer"),
    FSTAR_LEXER("fstar", "FStarLexer", "pygments.lexers.ml.FStarLexer"),
    OCAML_LEXER("ocaml", "OcamlLexer", "pygments.lexers.ml.OcamlLexer"),
    OPA_LEXER("opa", "OpaLexer", "pygments.lexers.ml.OpaLexer"),
    REASON_LEXER("reason", "ReasonLexer", "pygments.lexers.ml.ReasonLexer"),
    SML_LEXER("sml", "SMLLexer", "pygments.lexers.ml.SMLLexer"),
    BUGS_LEXER("bugs", "BugsLexer", "pygments.lexers.modeling.BugsLexer"),
    JAGS_LEXER("jags", "JagsLexer", "pygments.lexers.modeling.JagsLexer"),
    MODELICA_LEXER("modelica", "ModelicaLexer", "pygments.lexers.modeling.ModelicaLexer"),
    STAN_LEXER("stan", "StanLexer", "pygments.lexers.modeling.StanLexer"),
    MODULA2_LEXER("modula2", "Modula2Lexer", "pygments.lexers.modula2.Modula2Lexer"),
    MONTE_LEXER("monte", "MonteLexer", "pygments.lexers.monte.MonteLexer"),
    MOSEL_LEXER("mosel", "MoselLexer", "pygments.lexers.mosel.MoselLexer"),
    NCL_LEXER("ncl", "NCLLexer", "pygments.lexers.ncl.NCLLexer"),
    NIMROD_LEXER("nimrod", "NimrodLexer", "pygments.lexers.nimrod.NimrodLexer"),
    NIT_LEXER("nit", "NitLexer", "pygments.lexers.nit.NitLexer"),
    NIX_LEXER("nix", "NixLexer", "pygments.lexers.nix.NixLexer"),
    COMPONENTPASCAL_LEXER("componentpascal", "ComponentPascalLexer", "pygments.lexers.oberon.ComponentPascalLexer"),
    LOGOS_LEXER("logos", "LogosLexer", "pygments.lexers.objective.LogosLexer"),
    OBJECTIVEC_LEXER("objectivec", "ObjectiveCLexer", "pygments.lexers.objective.ObjectiveCLexer"),
    OBJECTIVECPP_LEXER("objectivecpp", "ObjectiveCppLexer", "pygments.lexers.objective.ObjectiveCppLexer"),
    SWIFT_LEXER("swift", "SwiftLexer", "pygments.lexers.objective.SwiftLexer"),
    OOC_LEXER("ooc", "OocLexer", "pygments.lexers.ooc.OocLexer"),
    OPENSCAD_LEXER("openscad", "OpenScadLexer", "pygments.lexers.openscad.OpenScadLexer"),
    PARASAIL_LEXER("parasail", "ParaSailLexer", "pygments.lexers.parasail.ParaSailLexer"),
    ANTLRACTIONSCRIPT_LEXER("antlractionscript", "AntlrActionScriptLexer", "pygments.lexers.parsers.AntlrActionScriptLexer"),
    ANTLRCSHARP_LEXER("antlrcsharp", "AntlrCSharpLexer", "pygments.lexers.parsers.AntlrCSharpLexer"),
    ANTLRCPP_LEXER("antlrcpp", "AntlrCppLexer", "pygments.lexers.parsers.AntlrCppLexer"),
    ANTLRJAVA_LEXER("antlrjava", "AntlrJavaLexer", "pygments.lexers.parsers.AntlrJavaLexer"),
    ANTLR_LEXER("antlr", "AntlrLexer", "pygments.lexers.parsers.AntlrLexer"),
    ANTLROBJECTIVEC_LEXER("antlrobjectivec", "AntlrObjectiveCLexer", "pygments.lexers.parsers.AntlrObjectiveCLexer"),
    ANTLRPERL_LEXER("antlrperl", "AntlrPerlLexer", "pygments.lexers.parsers.AntlrPerlLexer"),
    ANTLRPYTHON_LEXER("antlrpython", "AntlrPythonLexer", "pygments.lexers.parsers.AntlrPythonLexer"),
    ANTLRRUBY_LEXER("antlrruby", "AntlrRubyLexer", "pygments.lexers.parsers.AntlrRubyLexer"),
    EBNF_LEXER("ebnf", "EbnfLexer", "pygments.lexers.parsers.EbnfLexer"),
    RAGELC_LEXER("ragelc", "RagelCLexer", "pygments.lexers.parsers.RagelCLexer"),
    RAGELCPP_LEXER("ragelcpp", "RagelCppLexer", "pygments.lexers.parsers.RagelCppLexer"),
    RAGELD_LEXER("rageld", "RagelDLexer", "pygments.lexers.parsers.RagelDLexer"),
    RAGELEMBEDDED_LEXER("ragelembedded", "RagelEmbeddedLexer", "pygments.lexers.parsers.RagelEmbeddedLexer"),
    RAGELJAVA_LEXER("rageljava", "RagelJavaLexer", "pygments.lexers.parsers.RagelJavaLexer"),
    RAGEL_LEXER("ragel", "RagelLexer", "pygments.lexers.parsers.RagelLexer"),
    RAGELOBJECTIVEC_LEXER("ragelobjectivec", "RagelObjectiveCLexer", "pygments.lexers.parsers.RagelObjectiveCLexer"),
    RAGELRUBY_LEXER("ragelruby", "RagelRubyLexer", "pygments.lexers.parsers.RagelRubyLexer"),
    TREETOP_LEXER("treetop", "TreetopLexer", "pygments.lexers.parsers.TreetopLexer"),
    DELPHI_LEXER("delphi", "DelphiLexer", "pygments.lexers.pascal.DelphiLexer"),
    PORTUGOL_LEXER("portugol", "PortugolLexer", "pygments.lexers.pascal.PortugolLexer"),
    PAWN_LEXER("pawn", "PawnLexer", "pygments.lexers.pawn.PawnLexer"),
    SOURCEPAWN_LEXER("sourcepawn", "SourcePawnLexer", "pygments.lexers.pawn.SourcePawnLexer"),
    PERL6_LEXER("perl6", "Perl6Lexer", "pygments.lexers.perl.Perl6Lexer"),
    PERL_LEXER("perl", "PerlLexer", "pygments.lexers.perl.PerlLexer"),
    PHIX_LEXER("phix", "PhixLexer", "pygments.lexers.phix.PhixLexer"),
    PHP_LEXER("php", "PhpLexer", "pygments.lexers.php.PhpLexer"),
    PSYSHCONSOLE_LEXER("psyshconsole", "PsyshConsoleLexer", "pygments.lexers.php.PsyshConsoleLexer"),
    ZEPHIR_LEXER("zephir", "ZephirLexer", "pygments.lexers.php.ZephirLexer"),
    POINTLESS_LEXER("pointless", "PointlessLexer", "pygments.lexers.pointless.PointlessLexer"),
    PONY_LEXER("pony", "PonyLexer", "pygments.lexers.pony.PonyLexer"),
    PRAAT_LEXER("praat", "PraatLexer", "pygments.lexers.praat.PraatLexer"),
    PROCFILE_LEXER("procfile", "ProcfileLexer", "pygments.lexers.procfile.ProcfileLexer"),
    LOGTALK_LEXER("logtalk", "LogtalkLexer", "pygments.lexers.prolog.LogtalkLexer"),
    PROLOG_LEXER("prolog", "PrologLexer", "pygments.lexers.prolog.PrologLexer"),
    PROMQL_LEXER("promql", "PromQLLexer", "pygments.lexers.promql.PromQLLexer"),
    PRQL_LEXER("prql", "PrqlLexer", "pygments.lexers.prql.PrqlLexer"),
    PTX_LEXER("ptx", "PtxLexer", "pygments.lexers.ptx.PtxLexer"),
    CYTHON_LEXER("cython", "CythonLexer", "pygments.lexers.python.CythonLexer"),
    DG_LEXER("dg", "DgLexer", "pygments.lexers.python.DgLexer"),
    NUMPY_LEXER("numpy", "NumPyLexer", "pygments.lexers.python.NumPyLexer"),
    PYTHON2_LEXER("python2", "Python2Lexer", "pygments.lexers.python.Python2Lexer"),
    PYTHON2TRACEBACK_LEXER("python2traceback", "Python2TracebackLexer", "pygments.lexers.python.Python2TracebackLexer"),
    PYTHONCONSOLE_LEXER("pythonconsole", "PythonConsoleLexer", "pygments.lexers.python.PythonConsoleLexer"),
    PYTHON_LEXER("python", "PythonLexer", "pygments.lexers.python.PythonLexer"),
    PYTHONTRACEBACK_LEXER("pythontraceback", "PythonTracebackLexer", "pygments.lexers.python.PythonTracebackLexer"),
    K_LEXER("k", "KLexer", "pygments.lexers.q.KLexer"),
    Q_LEXER("q", "QLexer", "pygments.lexers.q.QLexer"),
    QLIK_LEXER("qlik", "QlikLexer", "pygments.lexers.qlik.QlikLexer"),
    QVTO_LEXER("qvto", "QVToLexer", "pygments.lexers.qvt.QVToLexer"),
    RCONSOLE_LEXER("rconsole", "RConsoleLexer", "pygments.lexers.r.RConsoleLexer"),
    RD_LEXER("rd", "RdLexer", "pygments.lexers.r.RdLexer"),
    S_LEXER("s", "SLexer", "pygments.lexers.r.SLexer"),
    SHEXC_LEXER("shexc", "ShExCLexer", "pygments.lexers.rdf.ShExCLexer"),
    SPARQL_LEXER("sparql", "SparqlLexer", "pygments.lexers.rdf.SparqlLexer"),
    TURTLE_LEXER("turtle", "TurtleLexer", "pygments.lexers.rdf.TurtleLexer"),
    REBOL_LEXER("rebol", "RebolLexer", "pygments.lexers.rebol.RebolLexer"),
    RED_LEXER("red", "RedLexer", "pygments.lexers.rebol.RedLexer"),
    RESOURCE_LEXER("resource", "ResourceLexer", "pygments.lexers.resource.ResourceLexer"),
    RIDE_LEXER("ride", "RideLexer", "pygments.lexers.ride.RideLexer"),
    RITA_LEXER("rita", "RitaLexer", "pygments.lexers.rita.RitaLexer"),
    RNCCOMPACT_LEXER("rnccompact", "RNCCompactLexer", "pygments.lexers.rnc.RNCCompactLexer"),
    ROBOCONFGRAPH_LEXER("roboconfgraph", "RoboconfGraphLexer", "pygments.lexers.roboconf.RoboconfGraphLexer"),
    ROBOCONFINSTANCES_LEXER("roboconfinstances", "RoboconfInstancesLexer", "pygments.lexers.roboconf.RoboconfInstancesLexer"),
    ROBOTFRAMEWORK_LEXER("robotframework", "RobotFrameworkLexer", "pygments.lexers.robotframework.RobotFrameworkLexer"),
    FANCY_LEXER("fancy", "FancyLexer", "pygments.lexers.ruby.FancyLexer"),
    RUBYCONSOLE_LEXER("rubyconsole", "RubyConsoleLexer", "pygments.lexers.ruby.RubyConsoleLexer"),
    RUBY_LEXER("ruby", "RubyLexer", "pygments.lexers.ruby.RubyLexer"),
    RUST_LEXER("rust", "RustLexer", "pygments.lexers.rust.RustLexer"),
    SAS_LEXER("sas", "SASLexer", "pygments.lexers.sas.SASLexer"),
    SAVI_LEXER("savi", "SaviLexer", "pygments.lexers.savi.SaviLexer"),
    SCDOC_LEXER("scdoc", "ScdocLexer", "pygments.lexers.scdoc.ScdocLexer"),
    APPLESCRIPT_LEXER("applescript", "AppleScriptLexer", "pygments.lexers.scripting.AppleScriptLexer"),
    CHAISCRIPT_LEXER("chaiscript", "ChaiscriptLexer", "pygments.lexers.scripting.ChaiscriptLexer"),
    EASYTRIEVE_LEXER("easytrieve", "EasytrieveLexer", "pygments.lexers.scripting.EasytrieveLexer"),
    HYBRIS_LEXER("hybris", "HybrisLexer", "pygments.lexers.scripting.HybrisLexer"),
    JCL_LEXER("jcl", "JclLexer", "pygments.lexers.scripting.JclLexer"),
    LSL_LEXER("lsl", "LSLLexer", "pygments.lexers.scripting.LSLLexer"),
    LUA_LEXER("lua", "LuaLexer", "pygments.lexers.scripting.LuaLexer"),
    LUAU_LEXER("luau", "LuauLexer", "pygments.lexers.scripting.LuauLexer"),
    MOOCODE_LEXER("moocode", "MOOCodeLexer", "pygments.lexers.scripting.MOOCodeLexer"),
    MINISCRIPT_LEXER("miniscript", "MiniScriptLexer", "pygments.lexers.scripting.MiniScriptLexer"),
    MOONSCRIPT_LEXER("moonscript", "MoonScriptLexer", "pygments.lexers.scripting.MoonScriptLexer"),
    REXX_LEXER("rexx", "RexxLexer", "pygments.lexers.scripting.RexxLexer"),
    SMARTGAMEFORMAT_LEXER("smartgameformat", "SmartGameFormatLexer", "pygments.lexers.sgf.SmartGameFormatLexer"),
    BASH_LEXER("bash", "BashLexer", "pygments.lexers.shell.BashLexer"),
    BASHSESSION_LEXER("bashsession", "BashSessionLexer", "pygments.lexers.shell.BashSessionLexer"),
    BATCH_LEXER("batch", "BatchLexer", "pygments.lexers.shell.BatchLexer"),
    EXECLINE_LEXER("execline", "ExeclineLexer", "pygments.lexers.shell.ExeclineLexer"),
    FISHSHELL_LEXER("fishshell", "FishShellLexer", "pygments.lexers.shell.FishShellLexer"),
    MSDOSSESSION_LEXER("msdossession", "MSDOSSessionLexer", "pygments.lexers.shell.MSDOSSessionLexer"),
    POWERSHELL_LEXER("powershell", "PowerShellLexer", "pygments.lexers.shell.PowerShellLexer"),
    POWERSHELLSESSION_LEXER("powershellsession", "PowerShellSessionLexer", "pygments.lexers.shell.PowerShellSessionLexer"),
    SLURMBASH_LEXER("slurmbash", "SlurmBashLexer", "pygments.lexers.shell.SlurmBashLexer"),
    TCSH_LEXER("tcsh", "TcshLexer", "pygments.lexers.shell.TcshLexer"),
    TCSHSESSION_LEXER("tcshsession", "TcshSessionLexer", "pygments.lexers.shell.TcshSessionLexer"),
    SIEVE_LEXER("sieve", "SieveLexer", "pygments.lexers.sieve.SieveLexer"),
    SLASH_LEXER("slash", "SlashLexer", "pygments.lexers.slash.SlashLexer"),
    NEWSPEAK_LEXER("newspeak", "NewspeakLexer", "pygments.lexers.smalltalk.NewspeakLexer"),
    SMALLTALK_LEXER("smalltalk", "SmalltalkLexer", "pygments.lexers.smalltalk.SmalltalkLexer"),
    SMITHY_LEXER("smithy", "SmithyLexer", "pygments.lexers.smithy.SmithyLexer"),
    NUSMV_LEXER("nusmv", "NuSMVLexer", "pygments.lexers.smv.NuSMVLexer"),
    SNOBOL_LEXER("snobol", "SnobolLexer", "pygments.lexers.snobol.SnobolLexer"),
    SOLIDITY_LEXER("solidity", "SolidityLexer", "pygments.lexers.solidity.SolidityLexer"),
    SOPHIA_LEXER("sophia", "SophiaLexer", "pygments.lexers.sophia.SophiaLexer"),
    OUTPUT_LEXER("output", "OutputLexer", "pygments.lexers.special.OutputLexer"),
    RAWTOKEN_LEXER("rawtoken", "RawTokenLexer", "pygments.lexers.special.RawTokenLexer"),
    TEXT_LEXER("text", "TextLexer", "pygments.lexers.special.TextLexer"),
    SPICE_LEXER("spice", "SpiceLexer", "pygments.lexers.spice.SpiceLexer"),
    MYSQL_LEXER("mysql", "MySqlLexer", "pygments.lexers.sql.MySqlLexer"),
    PLPGSQL_LEXER("plpgsql", "PlPgsqlLexer", "pygments.lexers.sql.PlPgsqlLexer"),
    POSTGRESCONSOLE_LEXER("postgresconsole", "PostgresConsoleLexer", "pygments.lexers.sql.PostgresConsoleLexer"),
    POSTGRESEXPLAIN_LEXER("postgresexplain", "PostgresExplainLexer", "pygments.lexers.sql.PostgresExplainLexer"),
    POSTGRES_LEXER("postgres", "PostgresLexer", "pygments.lexers.sql.PostgresLexer"),
    RQL_LEXER("rql", "RqlLexer", "pygments.lexers.sql.RqlLexer"),
    SQL_LEXER("sql", "SqlLexer", "pygments.lexers.sql.SqlLexer"),
    SQLITECONSOLE_LEXER("sqliteconsole", "SqliteConsoleLexer", "pygments.lexers.sql.SqliteConsoleLexer"),
    TRANSACTSQL_LEXER("transactsql", "TransactSqlLexer", "pygments.lexers.sql.TransactSqlLexer"),
    SRCINFO_LEXER("srcinfo", "SrcinfoLexer", "pygments.lexers.srcinfo.SrcinfoLexer"),
    STATA_LEXER("stata", "StataLexer", "pygments.lexers.stata.StataLexer"),
    SUPERCOLLIDER_LEXER("supercollider", "SuperColliderLexer", "pygments.lexers.supercollider.SuperColliderLexer"),
    TACT_LEXER("tact", "TactLexer", "pygments.lexers.tact.TactLexer"),
    TAL_LEXER("tal", "TalLexer", "pygments.lexers.tal.TalLexer"),
    TCL_LEXER("tcl", "TclLexer", "pygments.lexers.tcl.TclLexer"),
    TEAL_LEXER("teal", "TealLexer", "pygments.lexers.teal.TealLexer"),
    ANGULAR2HTML_LEXER("angular2html", "Angular2HtmlLexer", "pygments.lexers.templates.Angular2HtmlLexer"),
    ANGULAR2_LEXER("angular2", "Angular2Lexer", "pygments.lexers.templates.Angular2Lexer"),
    CHEETAHHTML_LEXER("cheetahhtml", "CheetahHtmlLexer", "pygments.lexers.templates.CheetahHtmlLexer"),
    CHEETAHJAVASCRIPT_LEXER("cheetahjavascript", "CheetahJavascriptLexer", "pygments.lexers.templates.CheetahJavascriptLexer"),
    CHEETAH_LEXER("cheetah", "CheetahLexer", "pygments.lexers.templates.CheetahLexer"),
    CHEETAHXML_LEXER("cheetahxml", "CheetahXmlLexer", "pygments.lexers.templates.CheetahXmlLexer"),
    COLDFUSIONCFC_LEXER("coldfusioncfc", "ColdfusionCFCLexer", "pygments.lexers.templates.ColdfusionCFCLexer"),
    COLDFUSIONHTML_LEXER("coldfusionhtml", "ColdfusionHtmlLexer", "pygments.lexers.templates.ColdfusionHtmlLexer"),
    COLDFUSION_LEXER("coldfusion", "ColdfusionLexer", "pygments.lexers.templates.ColdfusionLexer"),
    CSSDJANGO_LEXER("cssdjango", "CssDjangoLexer", "pygments.lexers.templates.CssDjangoLexer"),
    CSSERB_LEXER("csserb", "CssErbLexer", "pygments.lexers.templates.CssErbLexer"),
    CSSGENSHI_LEXER("cssgenshi", "CssGenshiLexer", "pygments.lexers.templates.CssGenshiLexer"),
    CSSPHP_LEXER("cssphp", "CssPhpLexer", "pygments.lexers.templates.CssPhpLexer"),
    CSSSMARTY_LEXER("csssmarty", "CssSmartyLexer", "pygments.lexers.templates.CssSmartyLexer"),
    DJANGO_LEXER("django", "DjangoLexer", "pygments.lexers.templates.DjangoLexer"),
    ERB_LEXER("erb", "ErbLexer", "pygments.lexers.templates.ErbLexer"),
    EVOQUEHTML_LEXER("evoquehtml", "EvoqueHtmlLexer", "pygments.lexers.templates.EvoqueHtmlLexer"),
    EVOQUE_LEXER("evoque", "EvoqueLexer", "pygments.lexers.templates.EvoqueLexer"),
    EVOQUEXML_LEXER("evoquexml", "EvoqueXmlLexer", "pygments.lexers.templates.EvoqueXmlLexer"),
    GENSHI_LEXER("genshi", "GenshiLexer", "pygments.lexers.templates.GenshiLexer"),
    GENSHITEXT_LEXER("genshitext", "GenshiTextLexer", "pygments.lexers.templates.GenshiTextLexer"),
    HANDLEBARSHTML_LEXER("handlebarshtml", "HandlebarsHtmlLexer", "pygments.lexers.templates.HandlebarsHtmlLexer"),
    HANDLEBARS_LEXER("handlebars", "HandlebarsLexer", "pygments.lexers.templates.HandlebarsLexer"),
    HTMLDJANGO_LEXER("htmldjango", "HtmlDjangoLexer", "pygments.lexers.templates.HtmlDjangoLexer"),
    HTMLGENSHI_LEXER("htmlgenshi", "HtmlGenshiLexer", "pygments.lexers.templates.HtmlGenshiLexer"),
    HTMLPHP_LEXER("htmlphp", "HtmlPhpLexer", "pygments.lexers.templates.HtmlPhpLexer"),
    HTMLSMARTY_LEXER("htmlsmarty", "HtmlSmartyLexer", "pygments.lexers.templates.HtmlSmartyLexer"),
    JAVASCRIPTDJANGO_LEXER("javascriptdjango", "JavascriptDjangoLexer", "pygments.lexers.templates.JavascriptDjangoLexer"),
    JAVASCRIPTERB_LEXER("javascripterb", "JavascriptErbLexer", "pygments.lexers.templates.JavascriptErbLexer"),
    JAVASCRIPTGENSHI_LEXER("javascriptgenshi", "JavascriptGenshiLexer", "pygments.lexers.templates.JavascriptGenshiLexer"),
    JAVASCRIPTPHP_LEXER("javascriptphp", "JavascriptPhpLexer", "pygments.lexers.templates.JavascriptPhpLexer"),
    JAVASCRIPTSMARTY_LEXER("javascriptsmarty", "JavascriptSmartyLexer", "pygments.lexers.templates.JavascriptSmartyLexer"),
    JSP_LEXER("jsp", "JspLexer", "pygments.lexers.templates.JspLexer"),
    LASSOCSS_LEXER("lassocss", "LassoCssLexer", "pygments.lexers.templates.LassoCssLexer"),
    LASSOHTML_LEXER("lassohtml", "LassoHtmlLexer", "pygments.lexers.templates.LassoHtmlLexer"),
    LASSOJAVASCRIPT_LEXER("lassojavascript", "LassoJavascriptLexer", "pygments.lexers.templates.LassoJavascriptLexer"),
    LASSOXML_LEXER("lassoxml", "LassoXmlLexer", "pygments.lexers.templates.LassoXmlLexer"),
    LIQUID_LEXER("liquid", "LiquidLexer", "pygments.lexers.templates.LiquidLexer"),
    MAKOCSS_LEXER("makocss", "MakoCssLexer", "pygments.lexers.templates.MakoCssLexer"),
    MAKOHTML_LEXER("makohtml", "MakoHtmlLexer", "pygments.lexers.templates.MakoHtmlLexer"),
    MAKOJAVASCRIPT_LEXER("makojavascript", "MakoJavascriptLexer", "pygments.lexers.templates.MakoJavascriptLexer"),
    MAKO_LEXER("mako", "MakoLexer", "pygments.lexers.templates.MakoLexer"),
    MAKOXML_LEXER("makoxml", "MakoXmlLexer", "pygments.lexers.templates.MakoXmlLexer"),
    MASON_LEXER("mason", "MasonLexer", "pygments.lexers.templates.MasonLexer"),
    MYGHTYCSS_LEXER("myghtycss", "MyghtyCssLexer", "pygments.lexers.templates.MyghtyCssLexer"),
    MYGHTYHTML_LEXER("myghtyhtml", "MyghtyHtmlLexer", "pygments.lexers.templates.MyghtyHtmlLexer"),
    MYGHTYJAVASCRIPT_LEXER("myghtyjavascript", "MyghtyJavascriptLexer", "pygments.lexers.templates.MyghtyJavascriptLexer"),
    MYGHTY_LEXER("myghty", "MyghtyLexer", "pygments.lexers.templates.MyghtyLexer"),
    MYGHTYXML_LEXER("myghtyxml", "MyghtyXmlLexer", "pygments.lexers.templates.MyghtyXmlLexer"),
    RHTML_LEXER("rhtml", "RhtmlLexer", "pygments.lexers.templates.RhtmlLexer"),
    SMARTY_LEXER("smarty", "SmartyLexer", "pygments.lexers.templates.SmartyLexer"),
    SQLJINJA_LEXER("sqljinja", "SqlJinjaLexer", "pygments.lexers.templates.SqlJinjaLexer"),
    SSP_LEXER("ssp", "SspLexer", "pygments.lexers.templates.SspLexer"),
    TEATEMPLATE_LEXER("teatemplate", "TeaTemplateLexer", "pygments.lexers.templates.TeaTemplateLexer"),
    TWIGHTML_LEXER("twightml", "TwigHtmlLexer", "pygments.lexers.templates.TwigHtmlLexer"),
    TWIG_LEXER("twig", "TwigLexer", "pygments.lexers.templates.TwigLexer"),
    VELOCITYHTML_LEXER("velocityhtml", "VelocityHtmlLexer", "pygments.lexers.templates.VelocityHtmlLexer"),
    VELOCITY_LEXER("velocity", "VelocityLexer", "pygments.lexers.templates.VelocityLexer"),
    VELOCITYXML_LEXER("velocityxml", "VelocityXmlLexer", "pygments.lexers.templates.VelocityXmlLexer"),
    XMLDJANGO_LEXER("xmldjango", "XmlDjangoLexer", "pygments.lexers.templates.XmlDjangoLexer"),
    XMLERB_LEXER("xmlerb", "XmlErbLexer", "pygments.lexers.templates.XmlErbLexer"),
    XMLPHP_LEXER("xmlphp", "XmlPhpLexer", "pygments.lexers.templates.XmlPhpLexer"),
    XMLSMARTY_LEXER("xmlsmarty", "XmlSmartyLexer", "pygments.lexers.templates.XmlSmartyLexer"),
    YAMLJINJA_LEXER("yamljinja", "YamlJinjaLexer", "pygments.lexers.templates.YamlJinjaLexer"),
    TERATERM_LEXER("teraterm", "TeraTermLexer", "pygments.lexers.teraterm.TeraTermLexer"),
    GHERKIN_LEXER("gherkin", "GherkinLexer", "pygments.lexers.testing.GherkinLexer"),
    TAP_LEXER("tap", "TAPLexer", "pygments.lexers.testing.TAPLexer"),
    GETTEXT_LEXER("gettext", "GettextLexer", "pygments.lexers.textfmts.GettextLexer"),
    HTTP_LEXER("http", "HttpLexer", "pygments.lexers.textfmts.HttpLexer"),
    IRCLOGS_LEXER("irclogs", "IrcLogsLexer", "pygments.lexers.textfmts.IrcLogsLexer"),
    KERNELLOG_LEXER("kernellog", "KernelLogLexer", "pygments.lexers.textfmts.KernelLogLexer"),
    NOTMUCH_LEXER("notmuch", "NotmuchLexer", "pygments.lexers.textfmts.NotmuchLexer"),
    TODOTXT_LEXER("todotxt", "TodotxtLexer", "pygments.lexers.textfmts.TodotxtLexer"),
    COQ_LEXER("coq", "CoqLexer", "pygments.lexers.theorem.CoqLexer"),
    ISABELLE_LEXER("isabelle", "IsabelleLexer", "pygments.lexers.theorem.IsabelleLexer"),
    THINGSDB_LEXER("thingsdb", "ThingsDBLexer", "pygments.lexers.thingsdb.ThingsDBLexer"),
    TLB_LEXER("tlb", "TlbLexer", "pygments.lexers.tlb.TlbLexer"),
    TLS_LEXER("tls", "TlsLexer", "pygments.lexers.tls.TlsLexer"),
    TNT_LEXER("tnt", "TNTLexer", "pygments.lexers.tnt.TNTLexer"),
    RTS_LEXER("rts", "RtsLexer", "pygments.lexers.trafficscript.RtsLexer"),
    TYPOSCRIPTCSSDATA_LEXER("typoscriptcssdata", "TypoScriptCssDataLexer", "pygments.lexers.typoscript.TypoScriptCssDataLexer"),
    TYPOSCRIPTHTMLDATA_LEXER("typoscripthtmldata", "TypoScriptHtmlDataLexer", "pygments.lexers.typoscript.TypoScriptHtmlDataLexer"),
    TYPOSCRIPT_LEXER("typoscript", "TypoScriptLexer", "pygments.lexers.typoscript.TypoScriptLexer"),
    TYPST_LEXER("typst", "TypstLexer", "pygments.lexers.typst.TypstLexer"),
    CSSUL4_LEXER("cssul4", "CSSUL4Lexer", "pygments.lexers.ul4.CSSUL4Lexer"),
    HTMLUL4_LEXER("htmlul4", "HTMLUL4Lexer", "pygments.lexers.ul4.HTMLUL4Lexer"),
    JAVASCRIPTUL4_LEXER("javascriptul4", "JavascriptUL4Lexer", "pygments.lexers.ul4.JavascriptUL4Lexer"),
    PYTHONUL4_LEXER("pythonul4", "PythonUL4Lexer", "pygments.lexers.ul4.PythonUL4Lexer"),
    UL4_LEXER("ul4", "UL4Lexer", "pygments.lexers.ul4.UL4Lexer"),
    XMLUL4_LEXER("xmlul4", "XMLUL4Lexer", "pygments.lexers.ul4.XMLUL4Lexer"),
    ICON_LEXER("icon", "IconLexer", "pygments.lexers.unicon.IconLexer"),
    UCODE_LEXER("ucode", "UcodeLexer", "pygments.lexers.unicon.UcodeLexer"),
    UNICON_LEXER("unicon", "UniconLexer", "pygments.lexers.unicon.UniconLexer"),
    URBISCRIPT_LEXER("urbiscript", "UrbiscriptLexer", "pygments.lexers.urbi.UrbiscriptLexer"),
    USD_LEXER("usd", "UsdLexer", "pygments.lexers.usd.UsdLexer"),
    VCL_LEXER("vcl", "VCLLexer", "pygments.lexers.varnish.VCLLexer"),
    VCLSNIPPET_LEXER("vclsnippet", "VCLSnippetLexer", "pygments.lexers.varnish.VCLSnippetLexer"),
    BOOGIE_LEXER("boogie", "BoogieLexer", "pygments.lexers.verification.BoogieLexer"),
    SILVER_LEXER("silver", "SilverLexer", "pygments.lexers.verification.SilverLexer"),
    VERIFPAL_LEXER("verifpal", "VerifpalLexer", "pygments.lexers.verifpal.VerifpalLexer"),
    VISUALPROLOGGRAMMAR_LEXER("visualprologgrammar", "VisualPrologGrammarLexer", "pygments.lexers.vip.VisualPrologGrammarLexer"),
    VISUALPROLOG_LEXER("visualprolog", "VisualPrologLexer", "pygments.lexers.vip.VisualPrologLexer"),
    VYPER_LEXER("vyper", "VyperLexer", "pygments.lexers.vyper.VyperLexer"),
    WAT_LEXER("wat", "WatLexer", "pygments.lexers.webassembly.WatLexer"),
    WEBIDL_LEXER("webidl", "WebIDLLexer", "pygments.lexers.webidl.WebIDLLexer"),
    CIRRU_LEXER("cirru", "CirruLexer", "pygments.lexers.webmisc.CirruLexer"),
    DUEL_LEXER("duel", "DuelLexer", "pygments.lexers.webmisc.DuelLexer"),
    QML_LEXER("qml", "QmlLexer", "pygments.lexers.webmisc.QmlLexer"),
    SLIM_LEXER("slim", "SlimLexer", "pygments.lexers.webmisc.SlimLexer"),
    XQUERY_LEXER("xquery", "XQueryLexer", "pygments.lexers.webmisc.XQueryLexer"),
    WGSL_LEXER("wgsl", "WgslLexer", "pygments.lexers.wgsl.WgslLexer"),
    WHILEY_LEXER("whiley", "WhileyLexer", "pygments.lexers.whiley.WhileyLexer"),
    WOWTOC_LEXER("wowtoc", "WoWTocLexer", "pygments.lexers.wowtoc.WoWTocLexer"),
    WREN_LEXER("wren", "WrenLexer", "pygments.lexers.wren.WrenLexer"),
    X10_LEXER("x10", "X10Lexer", "pygments.lexers.x10.X10Lexer"),
    XORG_LEXER("xorg", "XorgLexer", "pygments.lexers.xorg.XorgLexer"),
    YANG_LEXER("yang", "YangLexer", "pygments.lexers.yang.YangLexer"),
    YARA_LEXER("yara", "YaraLexer", "pygments.lexers.yara.YaraLexer"),
    ZIG_LEXER("zig", "ZigLexer", "pygments.lexers.zig.ZigLexer"),
    AWK_LEXER("awk", "AwkLexer", "pygments.lexers.textedit.AwkLexer");


    private final String languageString;
    private final String languageClassName;
    private final String languageClassFullPath;

    LexerEnum(String languageString, String languageClassName, String languageClassFullPath) {
        this.languageString = languageString;
        this.languageClassName = languageClassName;
        this.languageClassFullPath = languageClassFullPath;
    }

    public String getLanguageString() {
        return languageString;
    }

    public String getLanguageClassName() {
        return languageClassName;
    }

    public String getLanguageClassFullPath() {
        return languageClassFullPath;
    }

    // Parametre olarak gelen dil adina gore ilgili LexerEnum degerini bulan metod
    public static LexerEnum findByLanguageString(String language) {
        for (LexerEnum lexerEnum : LexerEnum.values()) {
            if (lexerEnum.languageString.equalsIgnoreCase(language)) {
                return lexerEnum;
            }
        }
        return null; // Dil bulunamazsa null donebilir veya istege göre bir hata isleme stratejisi uygulanabilir
    }

    // Parametre olarak gelen dil adina gore ilgili LexerEnum degerinin tam adini bulan metod
    public static String findClassNameByLanguageString(String language) {
        LexerEnum lexerEnum = findByLanguageString(language);
        return lexerEnum != null ? lexerEnum.languageClassName : null;
    }

    // Parametre olarak gelen dil adina gore ilgili LexerEnum degerinin tam yolunu bulan metod
    public static String findClassFullPathByLanguageString(String language) {
        LexerEnum lexerEnum = findByLanguageString(language);
        return lexerEnum != null ? lexerEnum.languageClassFullPath : null;
    }
}
